### ISSUE TITLE
Change the default storage location for Docker images and layers to use runner woker's volume.

### ISSUE THREAD

**Issue by dengliu** [runs-on/runner-images-for-aws#9]
When using a runner that contains an in stance storage, even the `/home/runner/_work` is mounted on the instance storage volume, the docker root volume is not mounted on the instance storage volume. This cause the job who uses `docker build` still using the root volume storage and runs out.
One workaround is changing `/etc/docker/daemon.json` in a step of the workflow. example provided as below
However, it would be great if runs-on can add it to their AMI.

```
2024-10-04T21:12:57.6990975Z /dev/nvme0n1p1  ext4       39G   14G   26G  34% /
2024-10-04T21:12:57.6994963Z /dev/md0        ext4      1.1T  796M  1.1T   1% /home/runner/_work
```

```
      - name: update docker data root
        run: |
          echo '{"data-root": "/home/runner/_work/docker"}' | sudo tee /etc/docker/daemon.json > /dev/null
          sudo systemctl restart docker
          sudo cat /etc/docker/daemon.json
```

**Comment by dengliu** [comment]
I have cut a PR to address this issue:
https://github.com/runs-on/runner-images-for-aws/pull/10

**Comment by crohr** [comment]
Thanks, could you try with a recent version of RunsOn, it should be fixed now.
